### ISSUE TITLE
Links are mostly broken

### ISSUE THREAD

**Issue by ecsv** [gtfierro/OM2P-mesh#1]
Just noticed that a lot of your links are broken. And maybe think about just using the repository https://github.com/ap51-flash/ap51-flash (for example with git-submodule) instead of copying the source to a subfolder in your repository. Your current approach makes it rather hard to identify which version you are using and do identify changes which should be merged back to https://github.com/ap51-flash/ap51-flash

**Comment by gtfierro** [comment]
Thanks for the feedback! This repository is over 4 years old and I'm not working on the project any more, which is why it feels unmaintained.
